name: "Build Armbian"
on:
  workflow_dispatch:
jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - uses: armbian/build@main
        with:
          armbian_token:     "${{ secrets.GITHUB_TOKEN }}"
          armbian_release:   "trixie"
          armbian_target:    "kernel"
          armbian_board:     "orangepi5-plus"
